trainer: SwAV

visual:
  _target_: timm.create_model
  model_name: resnet50
  zero_init_last: false  # Default argument in torchvision (backward compat).
  num_classes: 0

visual_projection:
  _target_: lgssl.modules.projection_mlp.ProjectionMLP
  input_dim: 2048
  fc_dims:
    - 2048
    - 128 

prototypes:
  _target_: torch.nn.Linear
  in_features: 128
  out_features: 3000
  bias: False

queue:
  length: 7680
  feat_dim: 128
  start_steps: 37500
  
temperature: 0.1
freeze_prototype_iters: 2503
